# Generated by Django 5.0.3 on 2024-03-25 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filmes',
        ),
        migrations.DeleteModel(
            name='Generos',
        ),
    ]
