# Generated by Django 5.0.3 on 2024-04-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_alter_filmes_preco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmes',
            options={'verbose_name': 'Filme', 'verbose_name_plural': 'Filmes'},
        ),
        migrations.AlterModelOptions(
            name='generos',
            options={'verbose_name': 'Gênero', 'verbose_name_plural': 'Gêneros'},
        ),
        migrations.AlterField(
            model_name='filmes',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='generos',
            name='genero',
            field=models.CharField(max_length=100, verbose_name='Gênero'),
        ),
    ]
